name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  test:
    needs: build
    uses: ./.github/workflows/test.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  publish:
    needs: [build, test]
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/publish.yml
    secrets:
      NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
