name: Test

on:
  workflow_call:
    secrets:
      CODECOV_TOKEN:
        required: false
  push:
    branches:
      - main
      - canary

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node via Volta
        uses: volta-cli/action@v5

      - name: Install dependencies
        run: yarn install --immutable

      - name: Install system binaryen
        run: sudo apt-get update && sudo apt-get install -y binaryen

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Download Build Artifacts
        uses: actions/download-artifact@v8
        with:
          name: build-artifacts

      - name: Test Rust modules
        run: yarn test:rs

      - name: Generate Rust coverage
        run: yarn test:rs:coverage

      - name: Test JS/TS modules & Generate coverage
        run: yarn test:js --coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
